// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2caK1K_tIkrJpxqQ45c5Uww1EGQVtRp0',
    appId: '1:949840319318:web:477b33facb87fc82d17cf7',
    messagingSenderId: '949840319318',
    projectId: 'my-shoe-store-project-3d218',
    authDomain: 'my-shoe-store-project-3d218.firebaseapp.com',
    storageBucket: 'my-shoe-store-project-3d218.firebasestorage.app',
    measurementId: 'G-N8J50XVNGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5sWx7AYgWIpTdU98j8CEFP6SbAD9NS0I',
    appId: '1:949840319318:android:81a7cad7ae343a2cd17cf7',
    messagingSenderId: '949840319318',
    projectId: 'my-shoe-store-project-3d218',
    storageBucket: 'my-shoe-store-project-3d218.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClB271SATkYenNe-8ZMqa3noaM9LC2GuM',
    appId: '1:949840319318:ios:dbcecdc04e69b8e8d17cf7',
    messagingSenderId: '949840319318',
    projectId: 'my-shoe-store-project-3d218',
    storageBucket: 'my-shoe-store-project-3d218.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClB271SATkYenNe-8ZMqa3noaM9LC2GuM',
    appId: '1:949840319318:ios:dbcecdc04e69b8e8d17cf7',
    messagingSenderId: '949840319318',
    projectId: 'my-shoe-store-project-3d218',
    storageBucket: 'my-shoe-store-project-3d218.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2caK1K_tIkrJpxqQ45c5Uww1EGQVtRp0',
    appId: '1:949840319318:web:11a489c3834225f5d17cf7',
    messagingSenderId: '949840319318',
    projectId: 'my-shoe-store-project-3d218',
    authDomain: 'my-shoe-store-project-3d218.firebaseapp.com',
    storageBucket: 'my-shoe-store-project-3d218.firebasestorage.app',
    measurementId: 'G-K8G3SJQZ6B',
  );

}